packages:
  - packages/**

autoInstallPeers: true

catalog:
  '@antfu/eslint-config': ^7.7.3
  '@arethetypeswrong/cli': ^0.18.2
  '@changesets/cli': ^2.30.0
  '@types/node': ^25.5.0
  changelogithub: ^14.0.0
  eslint: ^10.1.0
  publint: ^0.3.18
  semver: ^7.7.4
  simple-git: ^3.33.0
  tsdown: ^0.21.4
  typescript: ~5.9.3

catalogMode: prefer

cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

preferWorkspacePackages: true

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false

trustPolicy: no-downgrade
