name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for npm provenance with OIDC
      pull-requests: write # Required so the bot can open the PR

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.13.1
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # This step evaluates whether to open a PR or publish
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          # Custom versioning script:
          # It requires running `pnpm install` AFTER changesets updates the versions
          # in the package.json files, so the `pnpm-lock.yaml` is correctly updated in the PR.
          version: pnpm run version # assumes a script in package.json: "version": "changeset version && pnpm install --no-frozen-lockfile"

          # Command to publish the packages
          publish: pnpm exec changeset publish

          commit: "[ci] release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Forces the use of OIDC/Provenance instead of the classic token
          NPM_TOKEN: '' # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868

      # If the previous step published something (i.e. you merged the PR), we generate the GitHub release
      - name: Generate Changelog with Changelogithub
        if: steps.changesets.outputs.published == 'true'
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}